name: Build V8

on:
  push:
    branches: [ main ]
    paths:
    - 'V8_VERSION'
    - '.github/workflows/build-v8.yml'
    - 'v8-macos.sh'

jobs:
  version_reader:
    name: Get version number
    runs-on: ubuntu-latest
    outputs:
      v8_version: ${{ steps.got_version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - id: got_version
      run: |
        echo "::set-output name=version::$(<./V8_VERSION)"

  build_macos_arm64:
    name: macos-arm64
    runs-on: macos-latest
    needs: version_reader
    steps:
    - uses: actions/checkout@v4
    - name: Run build script
      run: |
        sh v8-macos.sh ${{ needs.version_reader.outputs.v8_version }}
    - uses: actions/upload-artifact@v4
      with:
        name: macos-arm64
        path: |
          output

  